apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
    name: xdostorages.storage.acw.alvsanand.github.io
    annotations:
        argocd.argoproj.io/sync-wave: "1"
spec:
    group: storage.acw.alvsanand.github.io
    names:
        kind: XDObjectStorage
        plural: xdostorages
    claimNames:
        kind: ObjectStorage
        plural: ostorages
    versions:
        - name: v1alpha1
          served: true
          referenceable: true
          schema:
              openAPIV3Schema:
                  type: object
                  properties:
                      spec:
                          type: object
                          properties:
                              parameters:
                                  type: object
                                  properties:
                                      storageName:
                                          type: string
                                  required:
                                      - storageName
                          required:
                              - parameters
